### ISSUE TITLE
Make a pajbot wiki

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1022]
Excellent example: https://github.com/Chatterino/wiki
Dead simple to make and we can collate variables and other information there (like an install guide)

**Comment by RAnders00** [comment]
What do you say we release the existing documentation to GitHub pages (https://pajbot.github.io/pajbot) on every release?

**Comment by alazymeme** [comment]
> What do you say we release the existing documentation to GitHub pages (https://pajbot.github.io/pajbot) on every release?

Yeah that'd probably work. Could probably use wiki.pajbot.com or some shit though

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.

**Comment by alazymeme** [comment]
I'm already working on this and it's more docs related than bot related. Can you reopen and assign me pls

**Comment by RAnders00** [comment]
I would appreciate if we could keep the footprint of all future documentation improvements small. That means adding .md files to this repo primarily. I don't think I want to invest the effort of building and keeping up a wiki, which arguably has only dubious benefits. The same work is better spent just writing the documentation instead of plumbing around with setting up a wiki and its infrastructure.

**Comment by RAnders00** [comment]
That means documentation improvments are still welcome, I would appreciate if you could integrate them into this repo as .md files instead though.
