### ISSUE TITLE
Socket Manager handlers

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#106]
Right now, Socket Manager handlers are run in the order they are added.
It's probably best if this is "recalculated" each time a handler is added, and just sort them by some sort of "priority".

**Comment by RiTu1337** [comment]
fite me irl

**Comment by TroyDota** [comment]
@pajlada is this still an issue?

**Comment by RAnders00** [comment]
The socket manager doesnt have priority arguments, still. And yes, there are events that are subscribed multiple times on which order does matter.

The `module.update` topic is subscribed `CommandManager` and `ModuleManager`. In this case it's important that the `ModuleManager` runs its handlers before `CommandManager` because ´CommandManager` compiles a list of commands based on the modules.

E.g. if you updated some setting for a command name, if CommandManager ran first then it would run through all the modules with their old, pre-update settings, in effect not getting the new command name.

I suppose it's not an issue right now but the enhancement stands.
