### ISSUE TITLE
Regex accent bug

### ISSUE THREAD

**Issue by TroyDota** [pajbot/pajbot#1163]
```
import re

pattern = re.compile(r"""(?<![^rЯг®\s\b!@#$%^&*()0-9.,/\\';:"\-=[\]`~_])[rЯг®]\.?\s*([Æeе3=≡@|*]|ks|io)\.?\s*([d]|i\}|\|\)|c[\|l])(\b|\s|[!@#$%^&*()0-9.,/\\';:"\-=[\]`~_])""", re.I)

assert pattern.match("red") != None

assert pattern.match("ЯED") != None
```

Test Passes

```
from unidecode import unidecode

print(unidecode("ЯED"))  #"IaED is a thing too"
```

it seems that the library for removing unicode is buggin on some characters.

perhaps, we find a better lib or we do 2 regex tests per message when remove accents is enabled to test both WITH and WITHOUT or allow the option to run 2 test?

**Comment by pajlada** [comment]
What do you mean by "is buggin"? Please expand on the issue

**Comment by TroyDota** [comment]
Well, I imagine its doing what is intended but it seems to convert some characters (`Я`) to other characters in a strange and unexpected way.

**Comment by RAnders00** [comment]
Я is `U+042F : CYRILLIC CAPITAL LETTER YA`, which is a hardcoded mapping in unidecode: https://github.com/avian2/unidecode/blob/a3f59f9ca4f980b336a9e9df4fa973afd24ac7f4/unidecode/x004.py#L49

If you want this mapping to be fixed you should take it to the contact described by the unidecode project: https://pypi.org/project/Unidecode/#contact (Note that the linked GitHub repo above is not the official repo, it's just a mirror)

**Comment by RAnders00** [comment]
Now that I read a bit more about unidecode, I don't think this is a bug in unidecode. Unidecode is meant for transliteration, since the above cyrillic character is "CYRILLIC CAPITAL LETTER YA" the transliteration of "Ia" seems correct from my understanding. So the actual issue is perhaps that we are abusing unidecode for something that it wasn't designed to do, which is to remove accents and un-weirdify characters that look similar to other latin characters/numbers etc.
