### ISSUE TITLE
Install Help

### ISSUE THREAD

**Issue by DairyWeb3638077** [pajbot/pajbot#1816]
You should create a YT vid on how to properly install the bot

**Comment by zneix** [comment]
Why though? This sounds like a terrible idea.
1. It's tedious, takes a lot of time to do, could be very specific depending on the setup and exact 1:1 wouldn't apply to everyone, video could be taken down, removed, god knows what else would happen with it.
2. Bot's code changes and so does documentation - once process for installation would get different then the video would be also outdated - would you need to create a whole new video from scratch? or keep the old one and make people follow a guide, copy exact steps and commands and then fail because things have changed since video has been published.
3. Already existing documentation in install-docs directory is so verbose, detailed and goes through every single step covering all possible issues you might encounter - just read it and if you didn't understand it, read it again from the beginning and I guarantee you that it's easy to install the bot thanks to these docs which even include example configuration files and systemd units.

**Comment by RAnders00** [comment]
I have a suspicion that you might be asking for a video tutorial because you‘re lacking the fundamental skills required to run a linux system or server. (If you had those skills, I‘m convinced following the written install docs would be a breeze).

For this reason I agree with zneix - if you are not able to follow the install docs just because you‘re lacking the general skills of "doing things on linux" or "administrating a linux server", then you should work on getting up to speed on that (instead of asking for an install video to follow verbatim), because that kind of knowledge is out of the scope of the pajbot project.

It would also be dangerous for us to invite inexperienced people to run a service on the open internet/run a server - wouldn‘t making a video tutorial also make it so we had to teach about how to secure the server, install security updates on it, etc..?

And last of all, we‘d be getting a whole lot more support requests for issues that are not really pajbot issues, and are more issues that general system administration knowledge could solve. (For example, if we made an install tutorial, and you got stuck on it, wouldn‘t you come to ask for help on the GitHub issues here on this project?)
