### ISSUE TITLE
New idea for gambling?

### ISSUE THREAD

**Issue by TlumpSC** [pajbot/pajbot#257]
What about a new gable idea?
Idea: Every x minutes ( 30? 60? 45? ) there will be a heist.
Entered by anyone for free by e.g. !bankheist.
There is a chance that it will fail (66%?) an a chance that all "winners" get an amount of points.
So why call it a "gamble"? 
Because if the heist fails ALL will be timeouted for x minutes/hours. (less time on small streams, 1 hour on forsens stream?)
Feedback would be nice, anyways only some idea i got :3

**Comment by Nacht123** [comment]
Not sure, but thats the same as `!roulette`,
it's just for a **group** but since you can do the same solo its **easier** for the user.
Group features are always a bit :tada: 

The X minutes/hours timeout feature is bad, most of the active chatter will join it and will get a timeout.
The chat will be **forced to be slow** and most of them will **whisper mods** to **get unbanned.**


Not sure if this feature would be used at all.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
