### ISSUE TITLE
Twitch API v5 Compatibility Inquiry

### ISSUE THREAD

**Issue by GosuPvP** [pajbot/pajbot#330]
Hey there,

I had a few questions.  First, is the bot going to be compatible with Twitch api v5 ?  Secondly, I wanted to know if you would possibly have an import script of some kind to facilitate entering data from revlobot's export file into the bot ?  Lastly, is there a way to rename the points into another name ? It's called Gosu Gold on my channel.

Thanks a lot for your help,

Gosu_PvP

**Comment by smashedr** [comment]
I was able to write a script to import the points:

https://gist.github.com/smashedr/7c605a948863f427dcaa0ff51214986b

It has no code to create a column if it does not exist yet, but that can be easily added if needed.

**Comment by smashedr** [comment]
I was able to change the text to say Gosu Gold; however I am not as familiar with flask as I am django so I didnt want to touch the route (URI); so that is still at /points/

Padlada, is it OK to change the route to /gosugold/ or will it break things?

https://squad.gosupvp.com/points/

**Comment by pajlada** [comment]
- Is the bot going to be compatible with Twitch api v5?
Yeah it will be V5 api compatible. Shouldn't be too much of a switch once that's required. For now I haven't bothered going over because there's nothing that's only available in V5 that we need.

Changing the point name isn't too difficult. Most places are already customized, I could make some sort of "string lookup" available everywhere (on website and in commands).
As for changing the actual link, I don't think that's too smart. Is that something that you would like @GosuPvP ?

**Comment by GosuPvP** [comment]
Firstly, thank you for your responses both on here and on twitch.

Thanks for confirming about the link, definitely leaving things as they are.  Regarding the string lookup, that would be amazing and we'd definitely appreciate that if you have the time for it.

Cheers !

**Comment by RAnders00** [comment]
Check out github.com/zwb3/twitch-api-v3-proxy
