### ISSUE TITLE
Create script to migrate StreamLabs points in

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#525]
requested by @alazymeme

**Comment by alazymeme** [comment]
Adding to this, not only Streamlabs; but also streamelements, streamlabs chatbot, phantombot, etc
Potentially allowing a full migration would be nice, I know that streamlabs chatbot allows for "backups" which could potentially be read by a script. Phantombot is also completely opensource, so that should be easier.

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
