### ISSUE TITLE
OpenSSL permission denied error

### ISSUE THREAD

**Issue by DatGuy1** [pajbot/pajbot#600]
When not running pajbot under sudo, the following happens: https://pastebin.com/wYhJ3Evz

**Comment by RAnders00** [comment]
This error occurs if you have websocket set up as `ssl=1` and the error occurs because the bot cannot read the file under `key_path` or `crt_path`.

I agree the error could be a lot more helpful, but it's raised outside out of our code.

I believe this is not a pajbot issue, unless we want to try and make the error message more helpful.

**Comment by RAnders00** [comment]
Also, just wanted to point this out: Running pajbot as `root` is not recommended, your original post makes it sound like you are running it with bare `sudo`.
