### ISSUE TITLE
topchatters/topwatchers command counts from that of the controlling channel

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#767]
![image](https://user-images.githubusercontent.com/12804673/73524035-f9ae1380-4457-11ea-83f9-f72c71aa7884.png)

**Comment by RAnders00** [comment]
Those bot users should have 0 watchtime unless they are joined to the main channel too.

`num_lines` are indeed counted from the control hub too. I would wager this should not be a problem generally once the bot has been running for a while, because normal users should always have more line farm than those bots.

**Comment by alazymeme** [comment]
I completely disagree - they should not be counted as joining chat at all. This is a single channel bot, and I'd say this is a bug. Similar to https://github.com/pajbot/pajbot/issues/543

**Comment by RAnders00** [comment]
When a user types in the control hub they are created as a user in the database if they don't exist. However, they don't count as "watching the stream" or as being in offline chat while being joined there.
I suspect on your bot nobody has any watchtime and it's just arbitrary who the bot picks as the "top watchers". Same deal for num_lines, everybody has 0 lines, so who gets picked as top chatters is also arbitrary/random.

**Comment by RAnders00** [comment]
this is quite low prio and being that pajbot is being moved into maintenance mode I'm closing this.
