### ISSUE TITLE
allow people to untime out others

### ISSUE THREAD

**Issue by Parrallax** [pajbot/pajbot#801]
you can timeout others but u cant untime out others

**Comment by alazymeme** [comment]
Paid timeouts allow you to timeout others; you shouldn't be allowed to untimeout others (as people could easily log onto alt accounts and untimeout their main account after possibly breaking twitch tos)

**Comment by pajlada** [comment]
What @alazymeme mentioned is partially why I often times don't have the paid timeout module enabled anymore - because if a user gets timed out by a moderator they can have their long timeout overriden by the short paid timeout from a random user.
For this to be effective, we basically have to keep track of the active paid timeout on the user and ensure that "untimeouts" are only allowed on those paid timeouts.

**Comment by RAnders00** [comment]
this suggestion could be a module setting

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
