### ISSUE TITLE
Add support for reply threads

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#995]
Did a bit of digging and found the below:

https://discuss.dev.twitch.tv/t/reply-threading/27657
https://twitter.com/WarthsYT/status/1293256740440608770

**Comment by RAnders00** [comment]
I'd say wait until Twitch announces official third-party support for replies. I don't think even 100% of normal Twitch chat users have replies enabled yet.

Also from the way the bot currently does replies, it would be a huge chore, editing all modules and command handlers to have a reference back to the original message, in order to be able to tag the reply message, but nevertheless I'm open to it

**Comment by RAnders00** [comment]
Due to pajbot [being moved into maintenance mode](https://github.com/pajbot/pajbot/blob/master/README.md) I'm closing this feature request.
